
lab3_mergesort: lab3_mergesort.o
	gcc -Wall -g -o lab3_mergesort lab3_mergesort.o

lab3_mergesort.o: lab3_mergesort.c
	gcc -c -Wall -o lab3_mergesort.o lab3_mergesort.c

.PHONY: clean

clean: rm -f *.o lab3_mergesort
